[no_features]
engine = "Llvm"
features = ""
run-types = ["Tests", "Doctests"]
release = false

[no_features_release]
engine = "Llvm"
features = ""
run-types = ["Tests", "Doctests"]
release = true

[ufmt]
engine = "Llvm"
features = "ufmt"
run-types = ["Tests", "Doctests"]
release = false

[ufmt_release]
engine = "Llvm"
features = "ufmt"
run-types = ["Tests", "Doctests"]
release = true
